client_id: Udv9o8RefW8dbw
secret: noH-06VVj3IZaasxdcfGCmFfroWG_w
user_agent: scrapping
br_subreddits:
    - aa
    - aa
    
us_subreddits:
    - aa
    - aa
   
crypto_subreddits:
    - aa
    - aa

